In [1]:
from stable_baselines3.common.env_util import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3 import A2C

import numpy as np

In [2]:
# There already exists an environment generator
# that will make and wrap atari environments correctly.
# Here we are also multi-worker training (n_envs=4 => 4 environments)
vec_env = make_atari_env("PongNoFrameskip-v4", n_envs=4, seed=0)
# Frame-stacking with 4 frames
vec_env = VecFrameStack(vec_env, n_stack=4)

model = A2C("CnnPolicy", vec_env, verbose=1)


Using cpu device
Wrapping the env in a VecTransposeImage.


In [3]:
model.learn(total_timesteps=25000)

------------------------------------
| time/                 |          |
|    fps                | 229      |
|    iterations         | 100      |
|    time_elapsed       | 8        |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -1.71    |
|    explained_variance | 0.00734  |
|    learning_rate      | 0.0007   |
|    n_updates          | 99       |
|    policy_loss        | 0.0996   |
|    value_loss         | 0.00448  |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 3.54e+03 |
|    ep_rew_mean        | -20.5    |
| time/                 |          |
|    fps                | 237      |
|    iterations         | 200      |
|    time_elapsed       | 16       |
|    total_timesteps    | 4000     |
| train/                |          |
|    entropy_loss       | -1.68    |
|    explained_variance | 0.000112 |
|    learning_rate      | 0.0007   |
|

In [4]:
# Testing the results with 10 episodes

obs = vec_env.reset()
episodes = 5

for ep in range(episodes):
    obs = vec_env.reset()
    done = np.array([False, False, False, False], dtype=bool)
    while not done.any():
        action, _states = model.predict(obs, deterministic=False)
        obs, rewards, done, info = vec_env.step(action)
        vec_env.render("human")
        print(rewards)

c:\Users\pablo\anaconda3\envs\RL\Lib\site-packages\gymnasium\utils\passive_env_checker.py:335: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  logger.warn(


[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[ 0. -1. -1.  0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[ 0.  0.  0. -1.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[-1.  0.  0.  0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[ 0. -1. -1.  0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[-1.  0.  0.  0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]


In [5]:
vec_env.close()

In [6]:
from stable_baselines3.common.env_util import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3 import A2C

In [7]:
# There already exists an environment generator
# that will make and wrap atari environments correctly.
# Here we are also multi-worker training (n_envs=2 => 2 environments)
vec_env = make_atari_env("ALE/Breakout-v5", n_envs=2, seed=0)
# Frame-stacking with 2 frames
vec_env = VecFrameStack(vec_env, n_stack=2)

model = A2C("CnnPolicy", vec_env, verbose=1)
model.learn(total_timesteps=25000)

Using cpu device
Wrapping the env in a VecTransposeImage.
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 263      |
|    ep_rew_mean        | 2.63     |
| time/                 |          |
|    fps                | 98       |
|    iterations         | 100      |
|    time_elapsed       | 10       |
|    total_timesteps    | 1000     |
| train/                |          |
|    entropy_loss       | -0.663   |
|    explained_variance | 0.161    |
|    learning_rate      | 0.0007   |
|    n_updates          | 99       |
|    policy_loss        | -0.255   |
|    value_loss         | 0.0649   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 246      |
|    ep_rew_mean        | 2.11     |
| time/                 |          |
|    fps                | 99       |
|    iterations         | 200      |
|    time_elapsed       | 20       |
|    total_timest

In [8]:
# Testing the results with 10 episodes
import numpy as np

obs = vec_env.reset()
episodes = 5

for ep in range(episodes):
    obs = vec_env.reset()
    done = np.array([False, False, False, False], dtype=bool)
    while not done.any():
        action, _states = model.predict(obs, deterministic=False)
        obs, rewards, done, info = vec_env.step(action)
        vec_env.render("human")
        print(rewards)

[0. 0.]
[0. 1.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[1. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 1.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]


In [9]:
vec_env.close()

: 