In [2]:
import numpy as np

In [8]:
# Definir los estados, acciones y la matriz de recompensas R
states = ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7']

# Movimientos no permitidos o malos: -100
# Movimientos buenos: 0
# Movimientos buenos con recompensa: 100
# Filas: estados actuales
# Columnas: estados siguientes
R = np.array([
    [-100, 0, 0, -100, -100, -100, -100],
    [-100, -100, 0, -100, -100, -100, -100],
    [-100, 0, -100, -100, 0, -100, -100],
    [-100, 0, 0, -100, 0, 0, -100],
    [-100, -100, 0, -100, -100, 0, 100],
    [-100, -100, -100, -100, 0, -100, 100],
    [-100, -100, -100, -100, 0, 0, 100]
])
print(R)

[[-100    0    0 -100 -100 -100 -100]
 [-100 -100    0 -100 -100 -100 -100]
 [-100    0 -100 -100    0 -100 -100]
 [-100    0    0 -100    0    0 -100]
 [-100 -100    0 -100 -100    0  100]
 [-100 -100 -100 -100    0 -100  100]
 [-100 -100 -100 -100    0    0  100]]


In [9]:
# Inicializar la matriz de calidad Q
Q = np.zeros((7, 7))
Q

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [10]:
# Parámetros de Q-Learning
gamma = 0.8 # Factor de descuento (importancia de las recompensas futuras)
alpha = 0.1 # Tasa de aprendizaje (importancia de las recompensas pasadas)
iterations = 1000 # Número de iteraciones
state = 0 # Estado inicial
history = [] # Historial de Q

# Algoritmo Q-Learning
for iteration in range(iterations):
    # Elegir un estado siguiente aleatorio
    next_state = np.random.choice(np.arange(0, 7))
    # Recompensa de ir del estado actual al siguiente
    R[state, next_state]
    # Actualizar Q
    Q[state, next_state] = R[state, next_state] + gamma * np.max(Q[next_state]) # Actualizar Q
    # Pasar al siguiente estado
    state = next_state
    # Mostrar Q cada 100 iteraciones
    if iteration % 100 == 0:
        print(Q)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[   0.         51.2       115.2         0.          0.          0.
  -100.      ]
 [   0.        -48.8       115.2       -36.         44.         72.16
    15.2     ]
 [   0.          0.         15.2        15.2       144.         72.16
    37.728   ]
 [   0.         51.2        64.        -36.        265.716736   80.
   132.14592 ]
 [   0.          0.          0.          0.         44.        144.
   332.14592 ]
 [-100.         -7.84       15.2        15.2        80.         72.16
   215.2     ]
 [ -59.04      -48.8        15.2       -36.        144.        172.16
   290.1824  ]]
[[  70.05871104   92.16        212.5733888   112.5733888   165.716736
   112.5733888   132.14592   ]
 [  70.05871104   70.05871104  212.5733888   -36.          165.716736
    72.16        132.14592   ]
 [  70.05871104  170.05871104  112.5733

In [11]:
Q

array([[150.09415959, 250.09415959, 312.61769949, 214.09415959,
        292.61769949, 295.27532767, 295.27532767],
       [150.09415959, 150.09415959, 312.61769949, 214.09415959,
        294.09415959, 294.09415959, 294.09415959],
       [150.09415959, 248.61769949, 212.61769949, 215.27532767,
        390.77212436, 294.09415959, 294.09415959],
       [148.61769949, 250.09415959, 312.61769949, 212.61769949,
        394.09415959, 392.61769949, 294.09415959],
       [150.09415959, 150.09415959, 310.77212436, 214.09415959,
        294.09415959, 395.27532767, 492.61769949],
       [150.09415959, 150.09415959, 212.61769949, 212.61769949,
        392.61769949, 292.61769949, 495.27532767],
       [150.09415959, 150.09415959, 212.61769949, 214.09415959,
        394.09415959, 395.27532767, 494.09415959]])

In [13]:
# Ruta óptima
state = 0
while state != 6:
    next_state = np.argmax(Q[state])
    print(f'{states[state]} -> {states[next_state]}')
    state += 1
print(f'{states[state]} -> {states[next_state]}')

S1 -> S3
S2 -> S3
S3 -> S5
S4 -> S5
S5 -> S7
S6 -> S7
S7 -> S7


# Solución Profesor
+ Incluye goal_state
+ Normalizar la matriz Q (Q/Q.max() * 100)